---
- name: manage local user
  hosts: localhost

  tasks:
    - set_fact: local_username="{{ansible_user_id}}"

- name: install docker
  hosts: localhost
  become: yes

  roles:
    - docker_server

  tasks:
    - user: name="{{local_username}}" groups=docker append=yes
