---
- name: install go 
  hosts: localhost

  tasks:
    - set_fact:
        archi: amd64
      when: ansible_userspace_architecture == "x86_64"

    - set_fact:
        archi: 386
      when: archi is undefined

    - set_fact:
        dlfile: "go{{go_version}}.{{ansible_system|lower}}-{{archi}}.tar.gz"
    - set_fact:
        homedir: "{{ansible_user_dir}}"

    - stat: path="{{homedir}}/{{dlfile}}"
      register: go_archive

    - name: download go archive
      get_url:
        url: "https://dl.google.com/go/{{dlfile}}"
        dest: "{{ansible_user_dir}}"
      when: go_archive.stat.exists == false

    - become: yes
      file:
        path: "/usr/local/go"
        state: directory
        mode: 0755

    - name: unarchive
      become: yes
      unarchive:
        src: "{{homedir}}/{{dlfile}}"
        dest: /usr/local
        remote_src: yes

    - name: patch .profile
      blockinfile:
        path: "{{ansible_user_dir}}/.profile"
        block: |
          if [ -d "/usr/local/go/bin" ] ; then
            export GOROOT=/usr/local/go
            export PATH="$PATH:$GOROOT/bin"
          fi
          if [ -d "$HOME/Dropbox/dev/go" ] ; then
            export GOPATH="$HOME/Dropbox/dev/go"
            export PATH="$PATH:$GOPATH/bin"
          fi


