---
- name: install uxrvt and plugins
  hosts: all

  tasks:
    - name: install package
      become: yes
      package:
        name: rxvt-unicode-256color
        state: latest

    - name: install font-size plugin
      become: yes
      get_url:
        url: 'https://raw.githubusercontent.com/majutsushi/urxvt-font-size/master/font-size'
        dest: /usr/lib/urxvt/perl/font-size

    - name: install .Xdefaults file
      file:
        src: "{{playbook_dir}}/../urxvt/.Xdefaults"
        dest: "$HOME/.Xdefaults"
        state: link
