---
- name: install uxrvt and plugins
  hosts: all

  tasks:
    - name: install package
      become: yes
      package:
        name: rxvt-unicode-256color
        state: latest

    - name: check lib dir
      become: yes
      file: path="/usr/local/lib/urxvt" state="directory" mode=0755 owner=root group=staff

    - name: install font-size plugin
      become: yes
      get_url:
        url: 'https://raw.githubusercontent.com/majutsushi/urxvt-font-size/master/font-size'
        dest: /usr/local/lib/urxvt/font-size

    - name: install keyboard-select plugin
      become: yes
      get_url:
        url: 'https://raw.githubusercontent.com/muennich/urxvt-perls/master/keyboard-select'
        dest: /usr/local/lib/urxvt/keyboard-select

    - name: install .Xdefaults file
      file:
        src: "{{playbook_dir}}/../urxvt/.Xdefaults"
        dest: "$HOME/.Xdefaults"
        state: link
