---
- name: go get powerline-go
  shell: "go get -u github.com/justjanne/powerline-go"

- file:
    path: "{{ansible_user_dir}}/.config/powerline-go"
    state: directory
    mode: 0755

- stat:
    path: "{{ansible_user_dir}}/.config/powerline-go/config.sh"
  register: pwrlconf

- name: default conf
  copy:
    dest: "{{ansible_user_dir}}/.config/powerline-go/default.sh"
    content: |
      #!/bin/bash
      # https://github.com/justjanne/powerline-go
      function _update_ps1() {
          PS1="$(powerline-go -error $?)"
      }

      if [ "$TERM" != "linux" ]; then
          PROMPT_COMMAND="_update_ps1; $PROMPT_COMMAND"
      fi

- name: set default config if not exist
  file:
    src: "{{ansible_user_dir}}/.config/powerline-go/default.sh"
    dest: "{{ansible_user_dir}}/.config/powerline-go/config.sh"
    state: link
  when: pwrlconf.stat.exists == false

- name: activate powerline shell prompt in bashrc
  lineinfile:
    path: "{{ansible_user_dir}}/.bashrc"
    regexp: '^if \[ -f ~/.config/powerline-go/config.sh *'
    line: 'if [ -f ~/.config/powerline-go/config.sh ]; then . ~/.config/powerline-go/config.sh ; fi'
