---
- name: Manage aliases 
  copy:
    dest: "~/.bash_aliases"
    content: |
      alias ll='ls -l'
      alias la='ls -A'
      alias l='ls -CF'

      CMD=$(which kubectl)
      if [ $? == 0 ] ; then
       source <(kubectl completion bash)
      fi

  
- name: Manage aliases for root
  become: yes
  blockinfile:
    dest: /root/.bashrc
    block: |
      export LS_OPTIONS='--color=auto'
      eval "`dircolors`"
      alias ls='ls $LS_OPTIONS'
      alias ll='ls $LS_OPTIONS -l'
      alias l='ls $LS_OPTIONS -lA'
